services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web 
    ports:
      - "3000:3000" 
    environment: 
      OPENAI_API_KEY: "anything" 
      BASE_URL: "http://chatgpt:5000" 
      CUSTOM_MODELS: "-all,+gpt-3.5-turbo"                # 非登录用户，免费用户
      # CUSTOM_MODELS: "-all,+gpt-3.5-turbo,gpt-4,gpt4o"  # Plus用户
    depends_on:
      - chatgpt 
    restart: unless-stopped

  chatgpt:
    image: adryfish/llm-web-api
    container_name: llm-web-api
    ports:
      - "5000:5000"
    # volumes:
    #   # 浏览器数据，如何要保留浏览器登录信息，需要配置
    #   - ./browser_data:/app/browser_data
    # environment:
      # PROXY_SERVER: ""          # 代理服务器地址
      # USER_AGENT: ""            # 浏览器User-Agent
      # OPENAI_LOGIN_TYPE: ""     # 登录类型,nologin or email
      # OPENAI_LOGIN_EMAIL: ""    # 登录邮箱
      # OPENAI_LOGIN_PASSWORD: "" # 登录密码
    restart: unless-stopped